name: enforce-dev-only-to-main

on:
  pull_request:
    branches:
      - main

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Allow only dev into main
        run: |
          if [ "${{ github.head_ref }}" != "dev" ]; then
            echo "Only dev can be merged into main."
            exit 1
          fi